# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26830ab7af51b34686e65553a4afdca34da1dfd657e0777406a8d3cc31be932980d144cdfe277d9348c038afc053d0811df430dd4d7dda867333810fc503321

test:
  secret_key_base: a4479b42e9f24cac9c9b9a45341715fe17bae92c0bcb93b5d269af3363e65cd12514710b357a2ddf18ed8f7ac64e68e1cdb117ffff626a0e70aac61035799ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
